version: '3.9'

services:
  # mongodb service
  mongo_db:
    container_name: db_container
    image: mongo:latest
    restart: always
    volumes:
      - mongo_db:/data/db
    ports:
      - 2717:27017

  api:
    container_name: node_api
    build: .
    ports:
      - 3000:3000
    environment:
      PORT : 3000
      MONGODB_URI : mongodb://mongo_db:27017
      DB_NAME : Demo
      Name : TanmaySingewar
    depends_on:
      - mongo_db
    volumes:
      - .:/usr/app

volumes:
  mongo_db: {}
